services:
  database:
    # Zdefiniuj obraz kontenera PostgreSQL
    image: postgres:16.2-alpine

    # Zawsze uruchamiaj kontener po jego zamknięciu, chyba że został ręcznie zatrzymany
    restart: unless-stopped

    # Zdefiniuj zmienne środowiskowe
    environment:
      # Nazwa bazy danych
      POSTGRES_DB: "GameVault"
      # Domyślny adminstrator bazy danych
      POSTGRES_USER: "gamevault-admin"
      # Pobierz hasło z pliku .env
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    # Zdefiniuj port
    ports:
      # Przekieruj port 5432 z kontenera na port 60824 hosta.
      # Dzięki temu można połączyć się z bazą danych używając adresu localhost:60824
      - "60824:5432"

    # Zdefiniuj wolumin
    volumes:
      # Zapisz dane bazy danych w folderze ./db-data
      # Przed wykonaniem komendy docker-compose up -d, upewni się, że folder ./db-data istnieje
      - "./db-data:/var/lib/postgresql/data"

