INSERT INTO "Games" (type_id, name, description, min_players, max_players, playing_time, first_year_released)
VALUES ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Splendor',
        'Collect gem tokens and acquire development cards to build a prosperous Renaissance-era gem empire.', 2, 4, 30,
        2014),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Splendor Duel',
        'Compete to collect gem tokens and acquire development cards in this two-player version of the popular game Splendor.',
        2, 2, 30, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Splendor: Marvel',
        'Collect Infinity Stones and recruit heroes to build the most powerful team in this Marvel-themed version of Splendor.',
        2, 4, 30, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Splendor: Cities of Splendor',
        'Expand your Splendor experience with four different expansions that introduce new mechanics and challenges.',
        2, 4, 30, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Azul',
        'Draft and place tiles to create stunning patterns on your player board and score points in this abstract strategy game.',
        2, 4, 45, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), '7 Wonders',
        'Compete to build the most impressive ancient civilization by drafting cards and developing your city in this strategy game.',
        3, 7, 30, 2010),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Catan: Seafarers',
        'Expand the world of Catan with this nautical-themed expansion that introduces seafaring and exploration.', 3,
        4, 120, 1997),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Concordia',
        'Build a thriving empire by strategically deploying your resources and establishing trade routes in this award-winning strategy game.',
        2, 5, 100, 2013),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Sushi Go Party!',
        'Draft sushi dishes and score points by creating the most delicious combinations in this fun and festive card game.',
        2, 8, 20, 2016),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Wingspan',
        'Compete to attract and collect the most beautiful birds by carefully managing your resources in this engine-building game.',
        1, 5, 60, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'Betrayal at House on the Hill',
        'Explore a haunted mansion and uncover its terrifying secrets in this thrilling horror-themed game with a twist.',
        3, 6, 60, 2004),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Viticulture',
        'Manage your own winery by planting vines, harvesting grapes, and producing fine wines in this worker-placement game.',
        2, 6, 90, 2015),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Catan: Explorers & Pirates',
        'Set sail for adventure and explore uncharted islands while fending off fierce pirates in this Catan expansion.',
        3, 4, 120, 2013),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Brass: Birmingham',
        'Build industrial networks, acquire resources, and strategically deploy your workers in this economic strategy game set in the Industrial Revolution.',
        2, 4, 120, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Antiquity',
        'Develop your ancient civilization by acquiring resources, constructing monuments, and advancing your culture in this strategic worker-placement game.',
        2, 4, 120, 2004),
       ((SELECT id FROM "GameTypes" WHERE name = 'Abstract'), 'Photosynthesis',
        'Grow and strategically position your trees to capture the most sunlight and gain victory points in this abstract strategy game.',
        2, 4, 60, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Rising Sun',
        'Engage in political and military conflicts as you strive to unite feudal Japan under your clan''s banner in this strategic area control game.',
        3, 5, 90, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Terraforming Mars: Prelude',
        'Prepare Mars for the arrival of future colonists by completing vital pre-terraforming projects in this expansion for Terraforming Mars.',
        1, 5, 90, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Tiny Towns',
        'Build a thriving village by cleverly arranging resource cubes and managing your limited board space in this compact game.',
        1, 6, 45, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Dune: Imperium',
        'Compete for control of the iconic planet Arrakis by carefully managing your resources and making strategic decisions in this deck-building game.',
        1, 4, 120, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'The Crew: Mission Deep Sea',
        'Work together as a team of deep-sea explorers to complete missions and coordinate your actions in this cooperative trick-taking game.',
        3, 5, 20, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'The Quacks of Quedlinburg',
        'Brew magical concoctions by drawing ingredient chips and managing your pot''s pressure in this unique push-your-luck game.',
        2, 4, 60, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Targi',
        'Compete to establish the most profitable trade routes and expand your merchant empire in this strategic game set in the Renaissance era.',
        2, 4, 90, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Cartographers',
        'Draw maps and score points by strategically placing terrain features in this roll-and-write game.', 1, 100, 30,
        2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Maracaibo',
        'Navigate the Caribbean seas and amass wealth through trade, piracy, and exploration in this strategy game set in the 17th century.',
        1, 4, 120, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Gizmos',
        'Build wacky contraptions and assemble quirky inventions by strategically drafting components and managing your resources.',
        2, 4, 60, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Kingdomino',
        'Draft and connect dominoes to build your kingdom and score points in this elegant tile-laying game.', 2, 4, 20,
        2016),
       ((SELECT id FROM "GameTypes" WHERE name = 'Abstract'), 'Sagrada',
        'Draft and place colorful dice to create stunning stained-glass window patterns and score points in this abstract strategy game.',
        1, 4, 30, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Fallout Shelter: The Board Game',
        'Manage your own Vault and lead your Dwellers to prosperity in this post-apocalyptic board game based on the popular video game.',
        2, 4, 60, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'The Isle of Cats',
        'Rescue and adopt adorable cats while strategically arranging them on your boat to score points in this delightful polyomino game.',
        1, 4, 90, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'The Crew: The Quest for Planet Nine',
        'Embark on a space mission to discover the mysterious Planet Nine in this cooperative trick-taking game.', 2, 5,
        20, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'The Mind',
        'Communicate without speaking and play cards in ascending order to complete levels and achieve a Zen-like state in this unique cooperative game.',
        2, 4, 15, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'Fallout: New California',
        'Explore the post-nuclear wasteland of New California and uncover hidden secrets in this narrative adventure board game set in the Fallout universe.',
        1, 4, 160, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'Nemesis',
        'Survive an alien-infested spaceship and complete your secret objectives while dealing with other players and the unpredictable game environment in this thematic survival horror game.',
        1, 5, 180, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Frosthaven',
        'Embark on a cooperative adventure in the frozen north and build a thriving outpost in this highly anticipated sequel to Gloomhaven.',
        1, 4, 120, 2021),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'Sleeping Gods',
        'Sail the mysterious and ever-changing world of the Wandering Sea in search of a way home in this narrative-driven adventure game.',
        1, 4, 120, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Obsession',
        'Manage a grand estate in 19th-century England by hosting lavish events, hiring servants, and courting suitors in this thematic strategy game.',
        1, 4, 90, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'Star Wars: Imperial Assault',
        'Lead a team of Rebel heroes or Imperial forces in tactical combat missions set in the Star Wars universe in this epic campaign-driven adventure game.',
        2, 5, 120, 2014),
       ((SELECT id FROM "GameTypes" WHERE name = 'Abstract'), 'Cascadia',
        'Draft and place habitat tiles to create diverse ecosystems and attract wildlife in this elegant and relaxing tile-laying game.',
        1, 4, 30, 2021),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Crokinole',
        'Flick discs and score points by landing them in the center hole of the board in this classic dexterity game.',
        2, 4, 30, 1876),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Kanban EV',
        'Manage an automotive factory by optimizing production processes, upgrading machinery, and meeting deadlines in this strategic worker-placement game.',
        1, 4, 120, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Blood Rage',
        'Lead your Viking clan to glory by pillaging villages, completing quests, and engaging in epic battles in this strategic area control game.',
        2, 4, 90, 2015),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Anachrony',
        'Prepare for an impending cataclysm by managing resources, constructing buildings, and recruiting workers in this strategic worker-placement game.',
        1, 4, 120, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'On Mars',
        'Establish a self-sustaining colony on Mars by managing resources, constructing buildings, and exploring the Red Planet in this thematic strategy game.',
        1, 4, 150, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Lisboa',
        'Rebuild the city of Lisbon after a devastating earthquake by constructing buildings, opening shops, and gaining favor with the nobility in this thematic strategy game.',
        1, 4, 120, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Clans of Caledonia',
        'Lead a Scottish clan to prosperity by managing resources, producing goods, and exporting them to foreign markets in this economic strategy game.',
        1, 4, 120, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Paladins of the West Kingdom',
        'Defend the kingdom and spread the faith by recruiting workers, constructing fortifications, and battling enemies in this strategic worker-placement game.',
        1, 4, 90, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Mechs vs. Minions',
        'Pilot powerful mechs and battle hordes of minions in this cooperative programming game set in the League of Legends universe.',
        2, 4, 90, 2016),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Terra Mystica',
        'Lead your faction to victory by terraforming the land, constructing buildings, and expanding your influence in this strategic Eurogame.',
        2, 5, 150, 2012),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Gaia Project',
        'Colonize space and terraform planets to build a thriving galactic civilization in this strategic game set in the Terra Mystica universe.',
        1, 4, 150, 2017),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'The Gallerist',
        'Manage an art gallery by acquiring and promoting works of art, attracting visitors, and expanding your influence in this thematic strategy game.',
        1, 4, 120, 2015),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Great Western Trail',
        'Herd cattle, deliver goods, and construct buildings as you compete to become the most successful rancher in this strategic game set in the American West.',
        2, 4, 150, 2016),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Race for the Galaxy',
        'Explore, settle, and develop planets to build a space empire in this fast-paced card game set in the distant future.',
        2, 4, 60, 2007),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Five Tribes: The Djinns of Naqala',
        'Bid, move, and manipulate tribes to gain control of the legendary city of Naqala in this strategic game set in the Arabian Nights universe.',
        2, 4, 60, 2014),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Fields of Arle',
        'Build a prosperous farm in the East Frisian moors by cultivating crops, raising livestock, and expanding your estate in this strategic game.',
        1, 2, 120, 2014),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Beyond the Sun',
        'Explore the galaxy, research advanced technologies, and build a space empire in this strategic game set in a future where humanity has colonized the stars.',
        2, 4, 120, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'El Grande',
        'Control regions of medieval Spain by deploying caballeros, influencing the court, and strategically managing your power in this classic area control game.',
        2, 5, 120, 1995),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'The Search for Planet X',
        'Compete to be the first to discover the elusive Planet X by analyzing data, deducing its location, and submitting your findings in this deduction game.',
        1, 4, 60, 2020),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'Tainted Grail: The Fall of Avalon',
        'Embark on a dark and epic Arthurian adventure in this narrative-driven campaign game set in a grim and twisted version of Camelot.',
        1, 4, 120, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Inis',
        'Lead your clan to victory by exploring, expanding, and conquering territories in this strategic game set in a mythical Celtic world.',
        2, 4, 90, 2016),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Architects of the West Kingdom',
        'Construct buildings, recruit apprentices, and manage resources to build the most impressive cathedral in this strategic worker-placement game.',
        1, 5, 80, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Trickerion: Legends of Illusion',
        'Compete to become the most renowned magician in the city of Magoria by performing illusions, recruiting assistants, and mastering the art of magic.',
        2, 4, 120, 2015),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Brass: Lancashire',
        'Build industrial networks, acquire resources, and strategically deploy your workers in this economic strategy game set in the Industrial Revolution.',
        2, 4, 120, 2007),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'Zombies!!!',
        'Survive the zombie apocalypse by fighting your way through hordes of undead and reaching the helipad for evacuation in this thematic survival horror game.',
        2, 6, 60, 2001),
       ((SELECT id FROM "GameTypes" WHERE name = 'Party'), 'Exploding Kittens',
        'Avoid exploding kittens and other hazards while playing cards to sabotage your opponents in this fast-paced party game.',
        2, 5, 15, 2015),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Roll for the Galaxy',
        'Build space empires by rolling dice, managing resources, and developing technologies in this dice-based adaptation of Race for the Galaxy',
        2, 5, 45, 2014),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'For Sale',
        'Buy and sell properties to earn the most money in this fast-paced card game that combines bidding and bluffing.',
        3, 6, 20, 1997),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Caylus',
        'Compete to build the most prestigious castle by constructing buildings, recruiting workers, and managing resources in this classic worker-placement game.',
        2, 5, 150, 2005),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'UNO',
        'Match colors and numbers to be the first to empty your hand of cards in this classic family card game.', 2, 10,
        30, 1971),
       ((SELECT id FROM "GameTypes" WHERE name = 'Abstract'), 'Tsuro',
        'Navigate your dragon token along the path of the board and avoid colliding with other players in this elegant and relaxing tile-laying game.',
        2, 8, 15, 2004),
       ((SELECT id FROM "GameTypes" WHERE name = 'Party'), 'Cards Against Humanity',
        'Fill in the blanks with outrageous and politically incorrect phrases to create the funniest and most shocking combinations in this party game for horrible people.',
        4, 30, 30, 2011),
       ((SELECT id FROM "GameTypes" WHERE name = 'Abstract'), 'Blokus',
        'Strategically place your pieces on the board to block your opponents and claim territory in this abstract strategy game.',
        2, 4, 20, 2000),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Ra',
        'Bid, bluff, and collect sets of tiles to score points and become the most successful pharaoh in this classic auction game.',
        2, 5, 60, 1999),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Suburbia',
        'Build a thriving city by strategically placing tiles, managing resources, and balancing your income and reputation in this city-building game.',
        1, 4, 90, 2012),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Seasons',
        'Draft powerful cards, summon familiars, and cast spells to become the most powerful mage in this strategic card game.',
        2, 4, 60, 2012),
       ((SELECT id FROM "GameTypes" WHERE name = 'Party'), 'BANG! The Dice Game',
        'Roll dice, shoot your opponents, and figure out who your allies are in this fast-paced party game set in the Wild West.',
        3, 8, 15, 2013),
       ((SELECT id FROM "GameTypes" WHERE name = 'Party'), 'Skull',
        'Bluff and bid your way to victory in this fast-paced game of deception and strategy.', 3, 6, 30, 2011),
       ((SELECT id FROM "GameTypes" WHERE name = 'Party'), 'Captain Sonar',
        'Engage in real-time submarine battles as you coordinate with your crew to track and destroy your opponents in this high-stakes party game.',
        2, 8, 60, 2016),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Ghost Stories',
        'Defend a village from vengeful spirits by coordinating your actions, managing resources, and using special abilities in this cooperative horror game.',
        1, 4, 60, 2008),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Dominant Species',
        'Compete to survive and thrive in a harsh prehistoric world by adapting to changing environments, evolving species, and dominating the food chain in this strategic game.',
        2, 6, 180, 2010),
       ((SELECT id FROM "GameTypes" WHERE name = 'Party'), 'Dixit: Odyssey',
        'Expand your Dixit experience with new cards, illustrations, and themes in this standalone expansion for the popular party game.',
        3, 12, 30, 2011),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Tapestry',
        'Build a civilization from the ground up by exploring, innovating, and expanding in this epic strategy game that spans centuries of history.',
        1, 5, 120, 2019),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Disney Villainous: The Worst Takes it All',
        'Compete to achieve your own devious objective and become the most villainous character in this Disney-themed strategy game.',
        2, 6, 50, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Underwater Cities',
        'Build and develop underwater cities by constructing buildings, managing resources, and expanding your influence in this strategic game.',
        1, 4, 120, 2018),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Harry Potter: Hogwarts Battle',
        'Defend Hogwarts from dark forces by recruiting allies, casting spells, and defeating villains in this cooperative deck-building game set in the Harry Potter universe.',
        2, 4, 60, 2016),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Russian Railroads',
        'Build railroads, develop industry, and advance technology to become the most successful railway company in this strategic game set in 19th-century Russia.',
        2, 4, 120, 2013),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Fluxx',
        'Play cards, change the rules, and win by adapting to the ever-changing game state in this unpredictable and chaotic card game.',
        2, 6, 30, 1997),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Trajan',
        'Compete to become the most influential figure in ancient Rome by managing resources, expanding territories, and completing objectives in this strategic game.',
        2, 4, 90, 2011),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Champions of Midgard',
        'Lead a Viking clan to glory by recruiting warriors, battling monsters, and completing quests in this strategic game set in the world of Norse mythology.',
        2, 4, 90, 2015),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Samurai',
        'Compete to control feudal Japan by placing tiles, collecting resources, and influencing regions in this classic area control game.',
        2, 4, 60, 1998),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Castle Panic',
        'Defend your castle from hordes of monsters by coordinating with your fellow players to protect the castle walls in this cooperative tower defense game.',
        1, 6, 60, 2009),
       ((SELECT id FROM "GameTypes" WHERE name = 'Abstract'), 'Stratego',
        'Deploy your army, outmaneuver your opponent, and capture the flag in this classic strategy game of hidden movement and deduction.',
        2, 2, 45, 1946),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Above and Below',
        'Build a village above ground and explore the caverns below in this storytelling game that combines worker placement and narrative adventure.',
        2, 4, 90, 2015),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'The Lord of the Rings',
        'Embark on a perilous journey to Mount Doom to destroy the One Ring and save Middle-earth in this cooperative adventure game based on J.R.R. Tolkien''s epic fantasy.',
        2, 5, 90, 2000),
       ((SELECT id FROM "GameTypes" WHERE name = 'Thematic'), 'Gloom',
        'Tell dark and twisted tales of tragedy and misfortune for your family of misfits in this macabre storytelling card game.',
        2, 5, 60, 2005),
       ((SELECT id FROM "GameTypes" WHERE name = 'Family'), 'Yahtzee',
        'Roll dice, score points, and shout "Yahtzee!" in this classic dice game of luck and strategy.', 2, 10, 30,
        1956),
       ((SELECT id FROM "GameTypes" WHERE name = 'Strategy'), 'Tichu',
        'Form sets, play cards, and call Tichu to score points and win tricks in this classic partnership climbing card game.',
        4, 4, 60, 1991),
       ((SELECT id FROM "GameTypes" WHERE name = 'Party'), 'Jenga',
        'Carefully remove blocks from the tower and stack them on top to build the tallest structure without causing it to collapse in this classic dexterity game.',
        1, 8, 15, 1983);

INSERT INTO "Categories"(name)
VALUES ('Dice'),
       ('Mythology'),
       ('Fighting'),
       ('Ancient'),
       ('Abstract Strategy'),
       ('Aviation/Flight'),
       ('City Building'),
       ('Civilization'),
       ('Card Game'),
       ('Pirates'),
       ('Murder/Mystery'),
       ('Trivia'),
       ('World War I'),
       ('Zombies'),
       ('Video Game Theme'),
       ('Real-time'),
       ('Music'),
       ('Movies/TV/Radio theme'),
       ('Miniatures'),
       ('Maze'),
       ('Math'),
       ('Farming'),
       ('Expansion for Base-game'),
       ('Exploration'),
       ('Educational');

INSERT INTO "GameCategories"(game_id, category_id)
VALUES ((SELECT id FROM "Games" WHERE name = 'UNO'), (SELECT id FROM "Categories" WHERE name = 'Card Game')),
       ((SELECT id FROM "Games" WHERE name = 'UNO'), (SELECT id FROM "Categories" WHERE name = 'Movies/TV/Radio theme')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'),
        (SELECT id FROM "Categories" WHERE name = 'Mythology')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'), (SELECT id FROM "Categories" WHERE name = 'Medieval')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'), (SELECT id FROM "Categories" WHERE name = 'Fantasy')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'), (SELECT id FROM "Categories" WHERE name = 'Dice')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'),
        (SELECT id FROM "Categories" WHERE name = 'Adventure')),
       ((SELECT id FROM "Games" WHERE name = 'Photosynthesis'),
        (SELECT id FROM "Categories" WHERE name = 'Abstract Strategy')),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'),
        (SELECT id FROM "Categories" WHERE name = 'Science Fiction')),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'),
        (SELECT id FROM "Categories" WHERE name = 'Movies/TV/Radio theme')),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'), (SELECT id FROM "Categories" WHERE name = 'Novel-based')),
       ((SELECT id FROM "Games" WHERE name = 'Tiny Towns'), (SELECT id FROM "Categories" WHERE name = 'Abstract Strategy')),
       ((SELECT id FROM "Games" WHERE name = 'Tiny Towns'), (SELECT id FROM "Categories" WHERE name = 'City Building')),
       ((SELECT id FROM "Games" WHERE name = 'The Crew: Mission Deep Sea'),
        (SELECT id FROM "Categories" WHERE name = 'Adventure')),
       ((SELECT id FROM "Games" WHERE name = 'The Crew: Mission Deep Sea'),
        (SELECT id FROM "Categories" WHERE name = 'Mythology')),
       ((SELECT id FROM "Games" WHERE name = 'The Crew: Mission Deep Sea'),
        (SELECT id FROM "Categories" WHERE name = 'Card Game')),
       ((SELECT id FROM "Games" WHERE name = 'Targi'), (SELECT id FROM "Categories" WHERE name = 'Card Game')),
       ((SELECT id FROM "Games" WHERE name = 'Kingdomino'), (SELECT id FROM "Categories" WHERE name = 'City Building')),
       ((SELECT id FROM "Games" WHERE name = 'Kingdomino'), (SELECT id FROM "Categories" WHERE name = 'Medieval')),
       ((SELECT id FROM "Games" WHERE name = 'The Isle of Cats'), (SELECT id FROM "Categories" WHERE name = 'Fantasy')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Categories" WHERE name = 'Adventure')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Categories" WHERE name = 'Exploration')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Categories" WHERE name = 'Fantasy')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Categories" WHERE name = 'Fighting')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Categories" WHERE name = 'Miniatures')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Categories" WHERE name = 'Adventure')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Categories" WHERE name = 'Horror')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Categories" WHERE name = 'Miniatures')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Categories" WHERE name = 'Science Fiction')),
       ((SELECT id FROM "Games" WHERE name = 'Sleeping Gods'), (SELECT id FROM "Categories" WHERE name = 'Adventure')),
       ((SELECT id FROM "Games" WHERE name = 'Sleeping Gods'), (SELECT id FROM "Categories" WHERE name = 'Exploration')),
       ((SELECT id FROM "Games" WHERE name = 'Sleeping Gods'), (SELECT id FROM "Categories" WHERE name = 'Fantasy')),
       ((SELECT id FROM "Games" WHERE name = 'Sleeping Gods'), (SELECT id FROM "Categories" WHERE name = 'Fighting')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'),
        (SELECT id FROM "Categories" WHERE name = 'Adventure')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'),
        (SELECT id FROM "Categories" WHERE name = 'Exploration')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'),
        (SELECT id FROM "Categories" WHERE name = 'Fighting')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'),
        (SELECT id FROM "Categories" WHERE name = 'Miniatures')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'),
        (SELECT id FROM "Categories" WHERE name = 'Movies/TV/Radio theme')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'),
        (SELECT id FROM "Categories" WHERE name = 'Science Fiction')),
       ((SELECT id FROM "Games" WHERE name = 'Anachrony'), (SELECT id FROM "Categories" WHERE name = 'Science Fiction')),
       ((SELECT id FROM "Games" WHERE name = 'Paladins of the West Kingdom'),
        (SELECT id FROM "Categories" WHERE name = 'Medieval')),
       ((SELECT id FROM "Games" WHERE name = 'El Grande'), (SELECT id FROM "Categories" WHERE name = 'Medieval')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Categories" WHERE name = 'Zombies')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Categories" WHERE name = 'Horror')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Categories" WHERE name = 'Exploration')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Categories" WHERE name = 'Fighting')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Categories" WHERE name = 'Miniatures')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'),
        (SELECT id FROM "Categories" WHERE name = 'Movies/TV/Radio theme')),
       ((SELECT id FROM "Games" WHERE name = 'Scrabble'), (SELECT id FROM "Categories" WHERE name = 'Word Game')),
       ((SELECT id FROM "Games" WHERE name = 'Tsuro'), (SELECT id FROM "Categories" WHERE name = 'Abstract Strategy')),
       ((SELECT id FROM "Games" WHERE name = 'Tsuro'), (SELECT id FROM "Categories" WHERE name = 'Fantasy')),
       ((SELECT id FROM "Games" WHERE name = 'BANG! The Dice Game'), (SELECT id FROM "Categories" WHERE name = 'Dice')),
       ((SELECT id FROM "Games" WHERE name = 'BANG! The Dice Game'), (SELECT id FROM "Categories" WHERE name = 'Fighting')),
       ((SELECT id FROM "Games" WHERE name = 'Skull'), (SELECT id FROM "Categories" WHERE name = 'Card Game')),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), (SELECT id FROM "Categories" WHERE name = 'Fantasy')),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), (SELECT id FROM "Categories" WHERE name = 'Fighting')),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), (SELECT id FROM "Categories" WHERE name = 'Horror')),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), (SELECT id FROM "Categories" WHERE name = 'Mythology')),
       ((SELECT id FROM "Games" WHERE name = 'Above and Below'), (SELECT id FROM "Categories" WHERE name = 'Adventure')),
       ((SELECT id FROM "Games" WHERE name = 'Above and Below'), (SELECT id FROM "Categories" WHERE name = 'City Building')),
       ((SELECT id FROM "Games" WHERE name = 'Above and Below'), (SELECT id FROM "Categories" WHERE name = 'Exploration')),
       ((SELECT id FROM "Games" WHERE name = 'Above and Below'), (SELECT id FROM "Categories" WHERE name = 'Fantasy')),
       ((SELECT id FROM "Games" WHERE name = 'Above and Below'), (SELECT id FROM "Categories" WHERE name = 'Farming')),
       ((SELECT id FROM "Games" WHERE name = 'The Lord of the Rings'),
        (SELECT id FROM "Categories" WHERE name = 'Adventure')),
       ((SELECT id FROM "Games" WHERE name = 'The Lord of the Rings'), (SELECT id FROM "Categories" WHERE name = 'Fantasy')),
       ((SELECT id FROM "Games" WHERE name = 'The Lord of the Rings'),
        (SELECT id FROM "Categories" WHERE name = 'Novel-based')),
       ((SELECT id FROM "Games" WHERE name = 'The Lord of the Rings'),
        (SELECT id FROM "Categories" WHERE name = 'Movies/TV/Radio theme')),
       ((SELECT id FROM "Games" WHERE name = 'Fluxx'), (SELECT id FROM "Categories" WHERE name = 'Card Game')),
       ((SELECT id FROM "Games" WHERE name = 'Fluxx'), (SELECT id FROM "Categories" WHERE name = 'Abstract Strategy'));

INSERT INTO "Mechanics"(name)
VALUES ('Action Drafting'),
       ('Action Queue'),
       ('Area Majority/Influence'),
       ('Grid Movement'),
       ('Set Collection'),
       ('Delayed Purchase'),
       ('Force Commitment'),
       ('Increase Value of Unchosen Resources'),
       ('Communication Limits'),
       ('Cooperative Game'),
       ('Scenario/Mission/Campaign Game'),
       ('Hidden Roles'),
       ('Modular Board'),
       ('Square Grid'),
       ('Campaign/Battle Card Driven'),
       ('Contracts'),
       ('Investment'),
       ('Open Drafting'),
       ('Pattern Building'),
       ('Variable Player Powers'),
       ('Worker Placement');

INSERT INTO "GameMechanics"(game_id, mechanic_id)
VALUES ((SELECT id FROM "Games" WHERE name = 'UNO'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'), (SELECT id FROM "Mechanics" WHERE name = 'Dice Rolling')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'), (SELECT id FROM "Mechanics" WHERE name = 'Set Collection')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'), (SELECT id FROM "Mechanics" WHERE name = 'Worker Placement')),
       ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'), (SELECT id FROM "Mechanics" WHERE name = 'Variable Player Powers')),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'), (SELECT id FROM "Mechanics" WHERE name = 'Delayed Purchase')),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'), (SELECT id FROM "Mechanics" WHERE name = 'Force Commitment')),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'), (SELECT id FROM "Mechanics" WHERE name = 'Increase Value of Unchosen Resources')),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'), (SELECT id FROM "Mechanics" WHERE name = 'Open Drafting')),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'), (SELECT id FROM "Mechanics" WHERE name = 'Worker Placement')),
       ((SELECT id FROM "Games" WHERE name = 'Tiny Towns'), (SELECT id FROM "Mechanics" WHERE name = 'Pattern Building')),
       ((SELECT id FROM "Games" WHERE name = 'Tiny Towns'), (SELECT id FROM "Mechanics" WHERE name = 'Player Elimination')),
       ((SELECT id FROM "Games" WHERE name = 'Tiny Towns'), (SELECT id FROM "Mechanics" WHERE name = 'End Game Bonuses')),
       ((SELECT id FROM "Games" WHERE name = 'Tiny Towns'), (SELECT id FROM "Mechanics" WHERE name = 'Variable Player Powers')),
       ((SELECT id FROM "Games" WHERE name = 'The Crew: Mission Deep Sea'), (SELECT id FROM "Mechanics" WHERE name = 'Communication Limits')),
       ((SELECT id FROM "Games" WHERE name = 'The Crew: Mission Deep Sea'), (SELECT id FROM "Mechanics" WHERE name = 'Cooperative Game')),
       ((SELECT id FROM "Games" WHERE name = 'The Crew: Mission Deep Sea'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'The Crew: Mission Deep Sea'), (SELECT id FROM "Mechanics" WHERE name = 'Scenario/Mission/Campaign Game')),
       ((SELECT id FROM "Games" WHERE name = 'Targi'), (SELECT id FROM "Mechanics" WHERE name = 'Set Collection')),
       ((SELECT id FROM "Games" WHERE name = 'Targi'), (SELECT id FROM "Mechanics" WHERE name = 'Worker Placement')),
       ((SELECT id FROM "Games" WHERE name = 'Targi'), (SELECT id FROM "Mechanics" WHERE name = 'End Game Bonuses')),
       ((SELECT id FROM "Games" WHERE name = 'Targi'), (SELECT id FROM "Mechanics" WHERE name = 'Modular Board')),
       ((SELECT id FROM "Games" WHERE name = 'Targi'), (SELECT id FROM "Mechanics" WHERE name = 'Open Drafting')),
       ((SELECT id FROM "Games" WHERE name = 'Targi'), (SELECT id FROM "Mechanics" WHERE name = 'Square Grid')),
       ((SELECT id FROM "Games" WHERE name = 'Kingdomino'), (SELECT id FROM "Mechanics" WHERE name = 'Tile Placement')),
       ((SELECT id FROM "Games" WHERE name = 'Kingdomino'), (SELECT id FROM "Mechanics" WHERE name = 'Open Drafting')),
       ((SELECT id FROM "Games" WHERE name = 'The Isle of Cats'), (SELECT id FROM "Mechanics" WHERE name = 'Open Drafting')),
       ((SELECT id FROM "Games" WHERE name = 'The Isle of Cats'), (SELECT id FROM "Mechanics" WHERE name = 'Set Collection')),
       ((SELECT id FROM "Games" WHERE name = 'The Isle of Cats'), (SELECT id FROM "Mechanics" WHERE name = 'Income')),
       ((SELECT id FROM "Games" WHERE name = 'The Isle of Cats'), (SELECT id FROM "Mechanics" WHERE name = 'Tile Placement')),
       ((SELECT id FROM "Games" WHERE name = 'The Isle of Cats'), (SELECT id FROM "Mechanics" WHERE name = 'Square Grid')),
       ((SELECT id FROM "Games" WHERE name = 'The Isle of Cats'), (SELECT id FROM "Mechanics" WHERE name = 'Pattern Building')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Mechanics" WHERE name = 'Cooperative Game')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Mechanics" WHERE name = 'Scenario/Mission/Campaign Game')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Mechanics" WHERE name = 'Variable Player Powers')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Mechanics" WHERE name = 'Modular Board')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Mechanics" WHERE name = 'Campaign/Battle Card Driven')),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), (SELECT id FROM "Mechanics" WHERE name = 'Grid Movement')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Mechanics" WHERE name = 'Campaign/Battle Card Driven')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Mechanics" WHERE name = 'Cooperative Game')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Mechanics" WHERE name = 'Dice Rolling')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Mechanics" WHERE name = 'Modular Board')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Mechanics" WHERE name = 'Player Elimination')),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Mechanics" WHERE name = 'Variable Player Powers')),
       ((SELECT id FROM "Games" WHERE name = 'Sleeping Gods'), (SELECT id FROM "Mechanics" WHERE name = 'Cooperative Game')),
       ((SELECT id FROM "Games" WHERE name = 'Sleeping Gods'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'Sleeping Gods'), (SELECT id FROM "Mechanics" WHERE name = 'Scenario/Mission/Campaign Game')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'), (SELECT id FROM "Mechanics" WHERE name = 'Dice Rolling')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'), (SELECT id FROM "Mechanics" WHERE name = 'Grid Movement')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'), (SELECT id FROM "Mechanics" WHERE name = 'Modular Board')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'), (SELECT id FROM "Mechanics" WHERE name = 'Scenario/Mission/Campaign Game')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'), (SELECT id FROM "Mechanics" WHERE name = 'Square Grid')),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'), (SELECT id FROM "Mechanics" WHERE name = 'Variable Player Powers')),
       ((SELECT id FROM "Games" WHERE name = 'Anachrony'), (SELECT id FROM "Mechanics" WHERE name = 'Contracts')),
       ((SELECT id FROM "Games" WHERE name = 'Anachrony'), (SELECT id FROM "Mechanics" WHERE name = 'Dice Rolling')),
       ((SELECT id FROM "Games" WHERE name = 'Anachrony'), (SELECT id FROM "Mechanics" WHERE name = 'Variable Player Powers')),
       ((SELECT id FROM "Games" WHERE name = 'Paladins of the West Kingdom'), (SELECT id FROM "Mechanics" WHERE name = 'End Game Bonuses')),
       ((SELECT id FROM "Games" WHERE name = 'Paladins of the West Kingdom'), (SELECT id FROM "Mechanics" WHERE name = 'Open Drafting')),
       ((SELECT id FROM "Games" WHERE name = 'Paladins of the West Kingdom'), (SELECT id FROM "Mechanics" WHERE name = 'Worker Placement')),
       ((SELECT id FROM "Games" WHERE name = 'El Grande'), (SELECT id FROM "Mechanics" WHERE name = 'Action Drafting')),
       ((SELECT id FROM "Games" WHERE name = 'El Grande'), (SELECT id FROM "Mechanics" WHERE name = 'Area Majority/Influence')),
       ((SELECT id FROM "Games" WHERE name = 'El Grande'), (SELECT id FROM "Mechanics" WHERE name = 'Auction/Bidding')),
       ((SELECT id FROM "Games" WHERE name = 'El Grande'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'El Grande'), (SELECT id FROM "Mechanics" WHERE name = 'Open Drafting')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Mechanics" WHERE name = 'Dice Rolling')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Mechanics" WHERE name = 'Grid Movement')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), (SELECT id FROM "Mechanics" WHERE name = 'Modular Board')),
       ((SELECT id FROM "Games" WHERE name = 'Scrabble'), (SELECT id FROM "Mechanics" WHERE name = 'Square Grid')),
       ((SELECT id FROM "Games" WHERE name = 'Tsuro'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'Tsuro'), (SELECT id FROM "Mechanics" WHERE name = 'Tile Placement')),
       ((SELECT id FROM "Games" WHERE name = 'Tsuro'), (SELECT id FROM "Mechanics" WHERE name = 'Player Elimination')),
       ((SELECT id FROM "Games" WHERE name = 'BANG! The Dice Game'), (SELECT id FROM "Mechanics" WHERE name = 'Dice Rolling')),
       ((SELECT id FROM "Games" WHERE name = 'BANG! The Dice Game'), (SELECT id FROM "Mechanics" WHERE name = 'Player Elimination')),
       ((SELECT id FROM "Games" WHERE name = 'BANG! The Dice Game'), (SELECT id FROM "Mechanics" WHERE name = 'Variable Player Powers')),
       ((SELECT id FROM "Games" WHERE name = 'Skull'), (SELECT id FROM "Mechanics" WHERE name = 'Auction/Bidding')),
       ((SELECT id FROM "Games" WHERE name = 'Skull'), (SELECT id FROM "Mechanics" WHERE name = 'Hand Management')),
       ((SELECT id FROM "Games" WHERE name = 'Skull'), (SELECT id FROM "Mechanics" WHERE name = 'Player Elimination')),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), (SELECT id FROM "Mechanics" WHERE name = 'Cooperative Game')),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), (SELECT id FROM "Mechanics" WHERE name = 'Dice Rolling')),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), (SELECT id FROM "Mechanics" WHERE name = 'Modular Board')),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), (SELECT id FROM "Mechanics" WHERE name = 'Variable Player Powers'));

INSERT INTO "GameReleases"(game_id, release_date, publisher, studio, language, price, extra_information)
VALUES
    ((SELECT id FROM "Games" WHERE name = 'UNO'), '1971-01-01', 'Mattel', 'Mattel', 'English', 30, null),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), '1989-01-10', 'Mattel', 'Mattel', 'Spanish', 49.99, null),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), '1979-09-20', 'Mattel', 'Mattel', 'Chinese', 80, null),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), '2024-02-20', 'Mattel', 'Mattel', 'French', 75.20, null),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), '2003-03-31', 'Mattel', 'Mattel', 'German', 10.32, 'Missing few cards'),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), '2010-01-12', 'Mattel', 'Mattel', 'English', 30, null),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), '2015-06-07', 'Mattel', 'Mattel', 'Polish', 56.99, null),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), '2019-01-01', 'Mattel', 'Mattel', 'English', 30, null),
    ((SELECT id FROM "Games" WHERE name = 'Champions of Midgard'), '2015-01-01', 'Grey Fox Games', 'Grey Fox Games', 'English', 60,
        'Includes Valhalla and Dark Mountains expansions'),
       ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'), '2020-01-01', 'Dire Wolf', 'Dire Wolf', 'English', 60, null),
       ((SELECT id FROM "Games" WHERE name = 'Tiny Towns'), '2019-01-01', 'AEG', 'Alderac Entertainment Group', 'English', 40, 'Includes Fortune expansion'),
       ((SELECT id FROM "Games" WHERE name = 'The Crew: Mission Deep Sea'), '2021-01-01', 'KOSMOS', 'KOSMOS', 'English', 15, null),
       ((SELECT id FROM "Games" WHERE name = 'Targi'), '2018-01-01', 'KOSMOS', 'KOSMOS', 'English', 30, 'Includes expansion'),
       ((SELECT id FROM "Games" WHERE name = 'Kingdomino'), '2016-01-01', 'Blue Orange Games', 'Blue Orange Games', 'English', 20, 'Includes Age of Giants expansion'),
       ((SELECT id FROM "Games" WHERE name = 'The Isle of Cats'), '2019-01-01', 'City of Games', 'City of Games', 'English', 50, 'Includes expansion'),
       ((SELECT id FROM "Games" WHERE name = 'Frosthaven'), '2021-01-01', 'Cephalofair Games', 'Cephalofair Games', 'English', 100, null),
       ((SELECT id FROM "Games" WHERE name = 'Nemesis'), '2018-01-01', 'Awaken Realms', 'Awaken Realms', 'English', 350, 'Includes Carnomorphs and Voidseeders expansions'),
       ((SELECT id FROM "Games" WHERE name = 'Sleeping Gods'), '2021-01-01', 'Red Raven Games', 'Red Raven Games', 'English', 230, 'Includes Tides of Ruin expansion'),
       ((SELECT id FROM "Games" WHERE name = 'Star Wars: Imperial Assault'), '2014-01-01', 'Fantasy Flight Games', 'Fantasy Flight Games', 'English', 100, 'Includes expansions'),
       ((SELECT id FROM "Games" WHERE name = 'Anachrony'), '2017-01-01', 'Mindclash Games', 'Mindclash Games', 'English', 60, null),
       ((SELECT id FROM "Games" WHERE name = 'Paladins of the West Kingdom'), '2019-01-01', 'Garphill Games', 'Garphill Games', 'English', 50, null),
       ((SELECT id FROM "Games" WHERE name = 'El Grande'), '1995-01-01', 'Hans im Glück', 'Hans im Glück', 'English', 40, null),
       ((SELECT id FROM "Games" WHERE name = 'Zombies!!!'), '2001-01-01', 'Twilight Creations', 'Twilight Creations', 'English', 30, 'Includes expansions'),
       ((SELECT id FROM "Games" WHERE name = 'Scrabble'), '1938-01-01', 'Hasbro', 'Hasbro', 'English', 80, null),
       ((SELECT id FROM "Games" WHERE name = 'Tsuro'), '2004-01-01', 'Calliope Games', 'Calliope Games', 'English', 30, null),
       ((SELECT id FROM "Games" WHERE name = 'BANG! The Dice Game'), '2013-01-01', 'dV Giochi', 'dV Giochi', 'English', 15, null),
       ((SELECT id FROM "Games" WHERE name = 'Skull'), '2011-01-01', 'Asmodee', 'Asmodee', 'English', 30, null),
       ((SELECT id FROM "Games" WHERE name = 'Ghost Stories'), '2008-01-01', 'Repos Production', 'Repos Production', 'English', 40, 'Includes White Moon expansion'),
       ((SELECT id FROM "Games" WHERE name = 'Above and Below'), '2015-01-01', 'Red Raven Games', 'Red Raven Games', 'English', 50, null),
       ((SELECT id FROM "Games" WHERE name = 'The Lord of the Rings'), '2000-01-01', 'Fantasy Flight Games', 'Fantasy Flight Games', 'English', 60, null),
       ((SELECT id FROM "Games" WHERE name = 'Fluxx'), '1997-01-01', 'Looney Labs', 'Looney Labs', 'English', 20, null),
       ((SELECT id FROM "Games" WHERE name = 'UNO'), '2010-01-01', 'Mattel', 'Mattel', 'Spanish', 10, null),
       ((SELECT id FROM "Games" WHERE name = 'Above and Below'), '2015-01-01', 'Red Raven Games', 'Red Raven Games', 'Portuguese', 50, null),
       ((SELECT id FROM "Games" WHERE name = 'The Lord of the Rings'), '2000-01-01', 'Fantasy Flight Games', 'Fantasy Flight Games', 'German', 60, null),
       ((SELECT id FROM "Games" WHERE name = 'Fluxx'), '1997-01-01', 'Looney Labs', 'Looney Labs', 'French', 50, 'Missing some cards'),
       ((SELECT id FROM "Games" WHERE name = 'Catan: Seafarers'), '1998-01-01', 'KOSMOS', 'KOSMOS', 'English', 40, 'Missing some pieces'),
       ((SELECT id FROM "Games" WHERE name = 'Caylus'), '2005-01-01', 'Ystari Games', 'Ystari Games', 'French', 50, null),
       ((SELECT id FROM "Games" WHERE name = 'Trajan'), '2011-01-01', 'HUCH!', 'HUCH!', 'German', 60, null),
       ((SELECT id FROM "Games" WHERE name = 'Blokus'), '2000-01-01', 'Mattel', 'Mattel', 'Spanish', 30, null),
       ((SELECT id FROM "Games" WHERE name = 'Dixit: Odyssey'), '2011-01-01', 'Libellud', 'Libellud', 'French', 180.20, null),
       ((SELECT id FROM "Games" WHERE name = 'Dixit: Odyssey'), '2011-01-01', 'Libellud', 'Libellud', 'English', 120, null),
       ((SELECT id FROM "Games" WHERE name = 'Dominant Species'), '2010-01-01', 'GMT Games', 'GMT Games', 'English', 80, null),
       ((SELECT id FROM "Games" WHERE name = 'Everdell'), '2018-01-01', 'Starling Games', 'Starling Games', 'English', 60, null),
       ((SELECT id FROM "Games" WHERE name = 'Exploding Kittens'), '2015-01-01', 'Exploding Kittens', 'Exploding Kittens', 'English', 20, null),
       ((SELECT id FROM "Games" WHERE name = 'Azul'), '2017-01-01', 'Plan B Games', 'Plan B Games', 'English', 80, null),
       ((SELECT id FROM "Games" WHERE name = 'Azul'), '2017-01-01', 'Plan B Games', 'Plan B Games', 'Spanish', 40, 'Missing some pieces'),
       ((SELECT id FROM "Games" WHERE name = 'Azul'), '2017-01-01', 'Plan B Games', 'Plan B Games', 'Portuguese', 120, null),
       ((SELECT id FROM "Games" WHERE name = 'Fallout Shelter: The Board Game'), '2020-01-01', 'Fantasy Flight Games', 'Fantasy Flight Games', 'English', 80, null),
       ((SELECT id FROM "Games" WHERE name = 'Catan: Seafarers'), '1998-01-01', 'KOSMOS', 'KOSMOS', 'English', 200, null),
       ((SELECT id FROM "Games" WHERE name = 'Catan: Explorers & Pirates'), '2013-01-01', 'KOSMOS', 'KOSMOS', 'English', 60, null);

INSERT INTO "Users"(username, email, password, first_name, last_name, role)
VALUES
    ('brownleopard167', 'yandel.caballero@example.com', crypt('adriana', gen_salt('bf', 10)), 'Yandel', 'Caballero', 'ADMIN'),
       ('bigdog363', 'dwayne.wells@example.com', crypt('lespaul', gen_salt('bf', 10)), 'Dwayne', 'Wells', 'USER'),
       ('beautifulladybug647', 'benjamin.nielsen@example.com', crypt('speakers', gen_salt('bf', 10)), 'Benjamin', 'Nielsen', 'USER'),
       ('redelephant587', 'santiago.yanez@example.com', crypt('winner', gen_salt('bf', 10)), 'Santiago', 'Yáñez', 'USER'),
       ('brownelephant395', 'kuzman.jeremic@example.com', crypt('marianne', gen_salt('bf', 10)), 'Kuzman', 'Jeremić', 'ADMIN'),
       ('bluerabbit488', 'cooper.wright@example.com', crypt('football1', gen_salt('bf', 10)), 'Cooper', 'Wright', 'USER'),
       ('brownbird726', 'philippe.patel@example.com', crypt('trevor', gen_salt('bf', 10)), 'Philippe', 'Patel', 'USER'),
       ('redtiger664', 'khwrwsh.hmdy@example.com', crypt('megan1', gen_salt('bf', 10)), 'کوروش', 'احمدی', 'USER'),
       ('silverleopard287', 'edwin.burkhart@example.com', crypt('solitude', gen_salt('bf', 10)), 'Edwin', 'Burkhart', 'USER'),
       ('blackbutterfly238', 'emaus.nascimento@example.com', crypt('jayhawks', gen_salt('bf', 10)), 'Emaús', 'Nascimento', 'USER'),
       ('beautifulpeacock570', 'eduardo.esteban@example.com', crypt('2727', gen_salt('bf', 10)), 'Eduardo', 'Esteban', 'USER'),
       ('brownleopard490', 'lauro.dias@example.com', crypt('racers', gen_salt('bf', 10)), 'Lauro', 'Dias', 'USER'),
       ('bluelion607', 'eduardo.smith@example.com', crypt('horizon', gen_salt('bf', 10)), 'Eduardo', 'Smith', 'USER'),
       ('smallladybug987', 'dhiraj.dhamdhame@example.com', crypt('blondes', gen_salt('bf', 10)), 'Dhiraj', 'Dhamdhame', 'USER'),
       ('lazyzebra393', 'mads.jorgensen@example.com', crypt('natalie', gen_salt('bf', 10)), 'Mads', 'Jørgensen', 'USER'),
       ('sadfrog211', 'ashton.patel@example.com', crypt('murphy', gen_salt('bf', 10)), 'Ashton', 'Patel', 'USER'),
       ('organicdog182', 'miguel.moreno@example.com', crypt('susan', gen_salt('bf', 10)), 'Miguel', 'Moreno', 'USER'),
       ('lazybear213', 'marvin.lynch@example.com', crypt('1a2b3c4d', gen_salt('bf', 10)), 'Marvin', 'Lynch', 'USER'),
       ('orangemeercat937', 'aalyrd.zraay@example.com', crypt('admiral', gen_salt('bf', 10)), 'علیرضا', 'زارعی', 'ADMIN'),
       ('yellowwolf708', 'felix.patel@example.com', crypt('hottest', gen_salt('bf', 10)), 'Felix', 'Patel', 'USER'),
       ('yellowzebra866', 'enes.girard@example.com', crypt('game', gen_salt('bf', 10)), 'Enes', 'Girard', 'USER'),
       ('tinyzebra562', 'mny.mrdy@example.com', crypt('hardball', gen_salt('bf', 10)), 'مانی', 'مرادی', 'USER'),
       ('beautifulgoose819', 'elliot.roger@example.com', crypt('achilles', gen_salt('bf', 10)), 'Elliot', 'Roger', 'USER'),
       ('silverwolf552', 'dnyl.slry@example.com', crypt('sales', gen_salt('bf', 10)), 'دانیال', 'سالاری', 'USER'),
       ('ticklishwolf937', 'juno.melo@example.com', crypt('rolling', gen_salt('bf', 10)), 'Juno', 'Melo', 'USER'),
       ('happyelephant398', 'mustafa.dalkiran@example.com', crypt('buffy', gen_salt('bf', 10)), 'Mustafa', 'Dalkıran', 'ADMIN'),
       ('sadsnake629', 'gaetan.joly@example.com', crypt('yesyes', gen_salt('bf', 10)), 'Gaëtan', 'Joly', 'USER'),
       ('greensnake233', 'austin.zhang@example.com', crypt('startrek', gen_salt('bf', 10)), 'Austin', 'Zhang', 'USER'),
       ('ticklishgoose127', 'martin.esparza@example.com', crypt('midori', gen_salt('bf', 10)), 'Martín', 'Esparza', 'USER'),
       ('brownwolf827', 'edward.wang@example.com', crypt('1987', gen_salt('bf', 10)), 'Edward', 'Wang', 'USER'),
       ('smallpeacock567', 'ronald.stamm@example.com', crypt('root', gen_salt('bf', 10)), 'Ronald', 'Stamm', 'USER'),
       ('blackleopard632', 'raghav.rajesh@example.com', crypt('smokes', gen_salt('bf', 10)), 'Raghav', 'Rajesh', 'USER'),
       ('bigkoala609', 'edwin.hoffman@example.com', crypt('grizzly', gen_salt('bf', 10)), 'Edwin', 'Hoffman', 'USER'),
       ('crazycat330', 'rajko.stosic@example.com', crypt('1220', gen_salt('bf', 10)), 'Rajko', 'Stošić', 'USER'),
       ('ticklishzebra301', 'morgan.brun@example.com', crypt('nice', gen_salt('bf', 10)), 'Morgan', 'Brun', 'USER'),
       ('tinyswan125', 'necati.tuzun@example.com', crypt('manchest', gen_salt('bf', 10)), 'Necati', 'Tüzün', 'USER'),
       ('organicmouse894', 'andre.burton@example.com', crypt('jaguar1', gen_salt('bf', 10)), 'Andre', 'Burton', 'USER'),
       ('whiteelephant931', 'heiko.saller@example.com', crypt('active', gen_salt('bf', 10)), 'Heiko', 'Saller', 'USER'),
       ('angrytiger902', 'romeu.caldeira@example.com', crypt('python', gen_salt('bf', 10)), 'Romeu', 'Caldeira', 'ADMIN'),
       ('brownleopard182', 'gunbir.saldanha@example.com', crypt('gaymen', gen_salt('bf', 10)), 'Gunbir', 'Saldanha', 'USER'),
       ('smallcat637', 'daniel.mortensen@example.com', crypt('erica', gen_salt('bf', 10)), 'Daniel', 'Mortensen', 'USER'),
       ('yellowtiger206', 'nooa.niemela@example.com', crypt('420420', gen_salt('bf', 10)), 'Nooa', 'Niemela', 'USER'),
       ('whitefrog396', 'jeronimo.quinones@example.com', crypt('mantle', gen_salt('bf', 10)), 'Jerónimo', 'Quiñones', 'USER'),
       ('silverleopard192', 'jeremiah.andrews@example.com', crypt('33333333', gen_salt('bf', 10)), 'Jeremiah', 'Andrews', 'USER'),
       ('whitedog925', 'frank.byrd@example.com', crypt('bigal', gen_salt('bf', 10)), 'Frank', 'Byrd', 'ADMIN'),
       ('greenleopard699', 'carter.gagnon@example.com', crypt('eddie1', gen_salt('bf', 10)), 'Carter', 'Gagnon', 'USER'),
       ('ticklishdog164', 'umut.bayindir@example.com', crypt('ross', gen_salt('bf', 10)), 'Umut', 'Bayındır', 'USER'),
       ('lazygorilla208', 'isauro.gomes@example.com', crypt('heidi', gen_salt('bf', 10)), 'Isauro', 'Gomes', 'USER'),
       ('greendog151', 'valdemar.viana@example.com', crypt('giorgio', gen_salt('bf', 10)), 'Valdemar', 'Viana', 'ADMIN'),
       ('purplekoala865', 'juan.gamboa@example.com', crypt('tetsuo', gen_salt('bf', 10)), 'Juan', 'Gamboa', 'USER'),
       ('smallfrog999', 'jackson.morris@example.com', crypt('snapper', gen_salt('bf', 10)), 'Jackson', 'Morris', 'ADMIN'),
       ('silverfrog736', 'milomir.krasic@example.com', crypt('johnboy', gen_salt('bf', 10)), 'Milomir', 'Krasić', 'ADMIN');

INSERT INTO "GameReviews"(game_id, user_id, rating, review) VALUES
    ((SELECT id FROM "Games" WHERE name = 'UNO'), (SELECT id FROM "Users" WHERE username = 'brownleopard167'), 5, 'Great game!'),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), (SELECT id FROM "Users" WHERE username = 'bigdog363'), 4, 'Fun game to play with friends'),
    ((SELECT id FROM "Games" WHERE name = 'UNO'), (SELECT id FROM "Users" WHERE username = 'beautifulladybug647'), 5, 'Classic game'),
    ((SELECT id FROM "Games" WHERE name = 'Catan: Seafarers'), (SELECT id FROM "Users" WHERE username = 'smallfrog999'), 5, 'Great expansion!'),
    ((SELECT id FROM "Games" WHERE name = 'Nemesis'), (SELECT id FROM "Users" WHERE username = 'redelephant587'), 5, 'Best game ever!'),
    ((SELECT id FROM "Games" WHERE name = 'Chess'), (SELECT id FROM "Users" WHERE username = 'admin'), 4, 'Chess is a classic game that never gets old. The strategic depth is unmatched, and it provides an engaging mental challenge every time.'),
    ((SELECT id FROM "Games" WHERE name = 'Carcassonne'), (SELECT id FROM "Users" WHERE username = 'admin'), 5, 'Carcassonne is a fantastic tile-laying game with beautiful artwork. The simple rules belie the depth of strategy involved in placing your tiles and meeples.'),
    ((SELECT id FROM "Games" WHERE name = 'Pandemic'), (SELECT id FROM "Users" WHERE username = 'redelephant587'), 3, 'Pandemic is a cooperative game that can be both tense and frustrating. It''s challenging to coordinate efforts and contain the outbreaks, but immensely satisfying when you succeed.'),
    ((SELECT id FROM "Games" WHERE name = 'Dominion'), (SELECT id FROM "Users" WHERE username = 'admin'), 4, 'Dominion kicked off the deck-building genre, and it''s still one of the best examples of it. The constantly evolving gameplay keeps each match fresh and engaging.'),
    ((SELECT id FROM "Games" WHERE name = 'Power Grid'), (SELECT id FROM "Users" WHERE username = 'redelephant587'), 2, 'Power Grid is a complex economic game that can feel overwhelming at first. The rulebook could be clearer, but once you understand the mechanics, it''s a tense and rewarding experience.'),
    ((SELECT id FROM "Games" WHERE name = 'Ticket to Ride'), (SELECT id FROM "Users" WHERE username = 'admin'), 5, 'Ticket to Ride is a gateway game that''s perfect for introducing new players to modern board games. The gameplay is simple to learn, but offers enough depth to keep experienced gamers engaged.'),
    ((SELECT id FROM "Games" WHERE name = 'Scrabble'), (SELECT id FROM "Users" WHERE username = 'whitefrog396'), 4, 'Scrabble is a classic word game that''s both challenging and fun. It''s a great way to flex your vocabulary muscles while enjoying some friendly competition.'),
    ((SELECT id FROM "Games" WHERE name = 'Codenames'), (SELECT id FROM "Users" WHERE username = 'angrytiger902'), 3, 'Codenames is a party game that''s easy to learn but difficult to master. It''s a great way to get a group of people laughing and thinking creatively.'),
    ((SELECT id FROM "Games" WHERE name = 'Gloomhaven'), (SELECT id FROM "Users" WHERE username = 'purplekoala865'), 5, 'Gloomhaven is an epic adventure game with a rich, branching narrative and deep tactical combat. It''s a massive undertaking, but incredibly rewarding for those willing to invest the time.'),
    ((SELECT id FROM "Games" WHERE name = 'Axis & Allies'), (SELECT id FROM "Users" WHERE username = 'admin'), 2, 'Axis & Allies is a classic war game that can take hours to play. The rulebook is dense, and the game can feel bogged down in minutiae, but it''s still a grand strategic experience for dedicated players.'),
    ((SELECT id FROM "Games" WHERE name = 'Root'), (SELECT id FROM "Users" WHERE username = 'angrytiger902'), 4, 'Root is a unique game with asymmetric factions and a delightful woodland theme. The gameplay is engaging and varied, and the production quality is top-notch.'),
    ((SELECT id FROM "Games" WHERE name = 'The Castles of Burgundy: Special Edition'), (SELECT id FROM "Users" WHERE username = 'admin'), 3, 'The Castles of Burgundy is a classic Euro game that combines tile-laying with resource management. It''s not the most exciting theme, but the gameplay is solid and rewarding for fans of the genre.'),
    ((SELECT id FROM "Games" WHERE name = 'Catan'), (SELECT id FROM "Users" WHERE username = 'angrytiger902'), 5, 'Catan is a classic settler game that introduced many people to the world of modern board games. The simple mechanics belie the depth of strategy involved in building settlements and trading resources.'),
    ((SELECT id FROM "Games" WHERE name = 'Splendor'), (SELECT id FROM "Users" WHERE username = 'crazycat330'), 4, 'Splendor is a gem of a game, pun intended. The gameplay is straightforward, but the decision-making is agonizing as you try to collect the right combinations of gems and cards.'),
    ((SELECT id FROM "Games" WHERE name = 'Azul'), (SELECT id FROM "Users" WHERE username = 'angrytiger902'), 3, 'Azul is a beautiful abstract game with a unique tile-drafting mechanic. It''s easy to learn but challenging to master, making it a great option for both casual and hardcore gamers.'),
    ((SELECT id FROM "Games" WHERE name = '7 Wonders'), (SELECT id FROM "Users" WHERE username = 'ticklishgoose127'), 4, '7 Wonders is a brilliant civilization-building game that manages to pack a lot of depth into a relatively short playtime. The card drafting mechanic is clever and engaging.'),
    ((SELECT id FROM "Games" WHERE name = 'Sushi Go Party!'), (SELECT id FROM "Users" WHERE username = 'ticklishgoose127'), 5, 'Sushi Go Party! is a delightful card-drafting game with a fun sushi theme. It''s easy to learn and great for both families and gamers alike.'),
    ((SELECT id FROM "Games" WHERE name = 'Wingspan'), (SELECT id FROM "Users" WHERE username = 'silverwolf552'), 2, 'Wingspan is a beautiful game with stunning artwork, but the gameplay can feel a bit fiddly and overly complex at times.'),
    ((SELECT id FROM "Games" WHERE name = 'Viticulture'), (SELECT id FROM "Users" WHERE username = 'organicdog182'), 4, 'Viticulture is a well-designed worker placement game with a unique theme revolving around running a vineyard. The gameplay is engaging and the components are high-quality.'),
    ((SELECT id FROM "Games" WHERE name = 'Tiny Towns'), (SELECT id FROM "Users" WHERE username = 'organicdog182'), 3, 'Tiny Towns is a clever little game that feels deceptively simple at first. The spatial puzzle of fitting buildings into your town provides a satisfying challenge.'),
    ((SELECT id FROM "Games" WHERE name = 'Dixit'), (SELECT id FROM "Users" WHERE username = 'admin'), 4, 'Dixit is a delightfully whimsical party game that encourages creativity and interpretation. The stunning artwork on the cards is a joy to behold.'),
    ((SELECT id FROM "Games" WHERE name = 'Arkham Horror'), (SELECT id FROM "Users" WHERE username = 'admin'), 3, 'Arkham Horror is a thrilling and challenging cooperative game set in the Lovecraftian universe. The theme and atmosphere are top-notch, but the rulebook can be daunting for new players.'),
    ((SELECT id FROM "Games" WHERE name = 'Terraforming Mars'), (SELECT id FROM "Users" WHERE username = 'admin'), 5, 'Terraforming Mars is a brilliant and deeply strategic game that combines resource management, engine building, and a fascinating theme. The gameplay is engaging and highly replayable.'),
    ((SELECT id FROM "Games" WHERE name = 'Scythe'), (SELECT id FROM "Users" WHERE username = 'admin'), 4, 'Scythe is a beautifully crafted game with an intriguing alternate history theme. The gameplay is a perfect blend of strategic planning, resource management, and tactical combat.'),
    ((SELECT id FROM "Games" WHERE name = 'Splendor: Marvel'), (SELECT id FROM "Users" WHERE username = 'beautifulpeacock570'), 3, 'Splendor: Marvel is a fun twist on the classic Splendor game, with a Marvel superhero theme. While the gameplay remains largely the same, the theme adds an extra layer of enjoyment for comic book fans.'),
    ((SELECT id FROM "Games" WHERE name = 'Concordia'), (SELECT id FROM "Users" WHERE username = 'beautifulpeacock570'), 4, 'Concordia is a solid and engaging Euro-style game that combines resource management, hand management, and strategic planning. The gameplay is streamlined and elegant, making it a great option for seasoned gamers.'),
    ((SELECT id FROM "Games" WHERE name = 'Betrayal at House on the Hill'), (SELECT id FROM "Users" WHERE username = 'admin'), 5, 'Betrayal at House on the Hill is a thrilling and unpredictable horror game with a unique haunted house theme. The sense of suspense and surprise keeps players on the edge of their seats.'),
    ((SELECT id FROM "Games" WHERE name = 'Catan: Explorers & Pirates'), (SELECT id FROM "Users" WHERE username = 'blackbutterfly238'), 3, 'Catan: Explorers & Pirates is a solid expansion for the classic Catan game, adding new mechanics and a pirate theme. While it provides some fresh gameplay, it can feel a bit tacked-on at times.'),
    ((SELECT id FROM "Games" WHERE name = 'Brass: Birmingham'), (SELECT id FROM "Users" WHERE username = 'beautifulpeacock570'), 4, 'Brass: Birmingham is a complex and rewarding economic strategy game that captures the industrial revolution era. The gameplay is deep and challenging, making it a great choice for experienced gamers.'),
    ((SELECT id FROM "Games" WHERE name = 'Antiquity'), (SELECT id FROM "Users" WHERE username = 'organicmouse894'), 2, 'Antiquity is a civilization-building game that tries to capture the grandeur of ancient empires. While the theme is interesting, the gameplay can feel overly complex and fiddly at times.'),
    ((SELECT id FROM "Games" WHERE name = 'Rising Sun'), (SELECT id FROM "Users" WHERE username = 'admin'), 5, 'Rising Sun is a visually stunning game that combines area control, resource management, and a unique Japanese feudal theme. The gameplay is tense and engaging, and the miniatures are truly impressive.'),
    ((SELECT id FROM "Games" WHERE name = 'Terraforming Mars: Prelude'), (SELECT id FROM "Users" WHERE username = 'organicmouse894'), 4, 'Terraforming Mars: Prelude is a solid expansion for the base game, adding new corporations and a prelude phase that enhances the strategic depth. It''s a must-have for fans of the original game.'),
    ((SELECT id FROM "Games" WHERE name = 'Dune: Imperium'), (SELECT id FROM "Users" WHERE username = 'brownleopard490'), 3, 'Dune: Imperium is a deck-building game set in the iconic Dune universe. While the theme is well-executed, the gameplay can feel a bit derivative of other deck-builders.'),
    ((SELECT id FROM "Games" WHERE name = 'The Quacks of Quedlinburg'), (SELECT id FROM "Users" WHERE username = 'admin'), 4, 'The Quacks of Quedlinburg is a delightful bag-building game with a quirky theme and engaging push-your-luck mechanics. The production quality and artwork are top-notch.'),
    ((SELECT id FROM "Games" WHERE name = 'Targi'), (SELECT id FROM "Users" WHERE username = 'bluelion607'), 5, 'Targi is a unique and captivating abstract game that combines tile-laying, area control, and pattern-building mechanics. It''s a refreshingly original game that offers a deep strategic experience.'),
    ((SELECT id FROM "Games" WHERE name = 'Cartographers'), (SELECT id FROM "Users" WHERE username = 'organicmouse894'), 4, 'Cartographers is a delightful flip-and-write game that simulates the process of mapping unexplored lands. The gameplay is simple yet engaging, making it a great choice for casual game nights.'),
    ((SELECT id FROM "Games" WHERE name = 'Maracaibo'), (SELECT id FROM "Users" WHERE username = 'admin'), 3, 'Maracaibo is a complex and thematic Euro-style game set in the Caribbean. While the theme is well-executed, the gameplay can feel a bit too convoluted and fiddly at times.'),
    ((SELECT id FROM "Games" WHERE name = 'Gizmos'), (SELECT id FROM "Users" WHERE username = 'smallladybug987'), 4, 'Gizmos is a fun and innovative game that combines engine-building mechanics with a delightful marble-rolling mechanism. The gameplay is engaging, and the production quality is excellent.'),
    ((SELECT id FROM "Games" WHERE name = 'Kingdomino'), (SELECT id FROM "Users" WHERE username = 'smallladybug987'), 5, 'Kingdomino is a brilliantly simple and addictive tile-laying game that''s perfect for both casual and hardcore gamers. The gameplay is easy to learn but offers surprising depth and replayability.'),
    ((SELECT id FROM "Games" WHERE name = 'Sagrada'), (SELECT id FROM "Users" WHERE username = 'smallladybug987'), 4, 'Sagrada is a beautiful and engaging dice-drafting game that combines pattern-building mechanics with a stained-glass theme. The gameplay is challenging and highly satisfying.');
